---
- include: update_all.yml
- include: deploy_java.yml
- include: provision_master.yml
- include: provision_worker.yml
- include: provision_static_consul.yml
# - include: datomic/init.yml
- include: deploy_docker.yml


  
  
