---
- hosts: worker-nodes
  tasks:
    - name: Install base packages
      become: true
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'dnsmasq'
        - 'unzip'
        - 'letsencrypt'

    - name: Download and install hashicorp tools
      become: true
      unarchive:
        src: "{{ item.url }}"
        dest: "/usr/local/bin"
        copy: no
        creates: "{{ item.creates }}"
      with_items:
        - url: "https://releases.hashicorp.com/nomad/0.5.0/nomad_0.5.0_linux_amd64.zip"
          creates: "/usr/local/bin/nomad"

    - name: Creating folders
      become: true
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/var/lib/nomad"
        - "/etc/nomad"

    - name: Nomad Systemd
      become: true
      template:
        src: "nomad_systemd.service.j2"
        dest: "/etc/systemd/system/nomad.service"
      notify:
        - reload systemd
        - restart nomad

    - name: Nomad config
      become: true
      template:
        src: "nomad_worker.hcl.j2"
        dest: "/etc/nomad/server.hcl"
      notify:
        - restart nomad

  handlers:
    - name: reload systemd
      become: true
      shell: "systemctl daemon-reload"

    - name: restart nomad
      become: true
      service:
        state: restarted
        enabled: yes
        name: nomad


        
