---
- hosts: static-zookeeper-nodes
  tasks:
    - name: Install pip for python
      become: true
      apt:
        name: python-pip
        state: present
        
    - name: Install docker-py
      become: true
      pip: name=docker-py
    
    - name: Create ZooKeeper folders
      become: true
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/etc/zookeeper"
        - "/var/lib/zookeeper"
        - "/var/lib/zookeeper_datalog"

    - name: Create ZooKeeper config file
      become: true
      template:
        src: zoo.cfg.j2
        dest: "/etc/zookeeper/zoo.cfg"

    - name: Create ZooKeeper ID file
      become: true
      template:
        src: zoo.id.j2
        dest: "/var/lib/zookeeper/myid"

    - name: Pull the ZooKeeper docker image
      become: true
      docker_image:
        name: "pieterbreed/zookeeper"

    - name: Start the ZooKeeper docker container
      become: true
      docker_container:
        name: "zookeeper"
        image: "pieterbreed/zookeeper"
        state: started
        restart: yes
        dns_servers:
          - "{{ ansible_eth0['ipv4']['address'] }}"
        published_ports:
          - "2181:2181"
          - "2888:2888"
          - "3888:3888"
        volumes:
          - "/etc/zookeeper/zoo.cfg:/conf/zoo.cfg"
          - "/var/lib/zookeeper:/data"
          - "/var/lib/zookeeper_datalog:/datalog"
        
         
