---
- hosts: worker-nodes
  tasks:
    - name: Install base packages
      become: true
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - 'dnsmasq'
        - 'unzip'

    - name: Download and install hashicorp tools
      become: true
      unarchive:
        src: "{{ item.url }}"
        dest: "/usr/local/bin"
        copy: no
        creates: "{{ item.creates }}"
      with_items:
        - url: "https://releases.hashicorp.com/nomad/0.4.1/nomad_0.4.1_linux_amd64.zip"
          creates: "/usr/local/bin/nomad"

    - name: Creating folders
      become: true
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/var/lib/nomad"
        - "/etc/nomad"
        - "/etc/dnsmasq.d"

    - name: Nomad config
      become: true
      template:
        src: "nomad_worker.hcl.j2"
        dest: "/etc/nomad/server.hcl"

    - name: Nomad Systemd
      become: true
      template:
        src: "nomad_systemd.service.j2"
        dest: "/etc/systemd/system/nomad.service"

    - name: dnsmasq config
      become: true
      template:
        src: "dnsmasq_config.j2"
        dest: "/etc/dnsmasq.d/10-consul"

    - name: reload systemd
      become: true
      shell: "systemctl daemon-reload"

    - name: Restart all the new services
      become: true
      service:
        state: restarted
        enabled: yes
        name: "{{ item }}"
      with_items:
        - "nomad"
        - "dnsmasq"

        
